import { useState } from "react";
import { useLocation } from "wouter";
import { useCreateUser } from "@workspace/api-client-react";
import PageHeader from "@/components/PageHeader";

const RIGHTS_OPTIONS = [
  { value: "store_manager",    label: "Store Manager" },
  { value: "store_supervisor", label: "Store Supervisor" },
  { value: "administrator",    label: "Administrator" },
] as const;

const BRANCH_OPTIONS = ["501", "511", "502"];

type Rights = "store_manager" | "store_supervisor" | "administrator";

export default function CreateAccount() {
  const [, setLocation] = useLocation();

  const [username, setUsername]           = useState("");
  const [forenames, setForenames]         = useState("");
  const [surname, setSurname]             = useState("");
  const [employeeNumber, setEmployeeNumber] = useState("");
  const [rights, setRights]               = useState<Rights>("store_manager");
  const [branchCode, setBranchCode]       = useState("501");
  const [savedUserId, setSavedUserId]     = useState<string | null>(null);
  const [errorMsg, setErrorMsg]           = useState("");
  const [isActive, setIsActive]           = useState(true);

  const { mutate: createUser, isPending } = useCreateUser({
    mutation: {
      onSuccess: (data) => {
        setSavedUserId(data.userId);
        setErrorMsg("");
      },
      onError: (err: any) => {
        setErrorMsg(err?.data?.error ?? "Failed to create account");
      },
    },
  });

  const handleActivate = () => {
    if (!username || !forenames || !surname || !employeeNumber) {
      setErrorMsg("Please fill in all fields");
      return;
    }
    setIsActive(true);
    createUser({ data: { username, forenames, surname, employeeNumber, rights, storeBranchCode: branchCode, isActive: true } });
  };

  const handleDeactivate = () => {
    if (!username || !forenames || !surname || !employeeNumber) {
      setErrorMsg("Please fill in all fields");
      return;
    }
    setIsActive(false);
    createUser({ data: { username, forenames, surname, employeeNumber, rights, storeBranchCode: branchCode, isActive: false } });
  };

  return (
    <div className="min-h-screen w-full flex flex-col" style={{ backgroundColor: "#1e3f7a" }}>
      <PageHeader
        title={`Account: ${username || "(username)"}`}
        breadcrumb="Home/Create New Account"
      />

      {/* Form table */}
      <main className="flex-1 flex flex-col items-start px-8 pt-4 pb-6">
        <div className="w-full max-w-3xl">

          {/* Success message */}
          {savedUserId && (
            <div className="mb-3 px-4 py-2 rounded-lg bg-green-600/80 text-white text-sm font-medium">
              Account created! User ID: <strong>{savedUserId}</strong>
            </div>
          )}
          {errorMsg && (
            <div className="mb-3 px-4 py-2 rounded-lg bg-red-600/80 text-white text-sm font-medium">
              {errorMsg}
            </div>
          )}

          {/* Table */}
          <div className="rounded-xl overflow-hidden border border-white/10">
            {/* Header row */}
            <div className="grid grid-cols-2" style={{ backgroundColor: "#c8cdd6" }}>
              <div className="px-5 py-3 font-bold text-gray-800 text-sm border-r border-white/30">User ID</div>
              <div className="px-5 py-3 font-bold text-gray-800 text-sm">
                {savedUserId ?? "Autogenerated"}
              </div>
            </div>

            {/* Username */}
            <TableRow label="Username">
              <input
                type="text"
                value={username}
                onChange={(e) => { setUsername(e.target.value); setErrorMsg(""); setSavedUserId(null); }}
                placeholder="e.g. John_Doe"
                className="w-full bg-transparent outline-none text-gray-800 placeholder-gray-400 text-sm"
              />
            </TableRow>

            {/* Forenames */}
            <TableRow label="Fore Name(s)" alt>
              <input
                type="text"
                value={forenames}
                onChange={(e) => { setForenames(e.target.value); setErrorMsg(""); setSavedUserId(null); }}
                placeholder="e.g. John"
                className="w-full bg-transparent outline-none text-gray-800 placeholder-gray-400 text-sm"
              />
            </TableRow>

            {/* Surname */}
            <TableRow label="Surname">
              <input
                type="text"
                value={surname}
                onChange={(e) => { setSurname(e.target.value); setErrorMsg(""); setSavedUserId(null); }}
                placeholder="e.g. Doe"
                className="w-full bg-transparent outline-none text-gray-800 placeholder-gray-400 text-sm"
              />
            </TableRow>

            {/* Employee Number */}
            <TableRow label="Employee Number" alt>
              <input
                type="text"
                value={employeeNumber}
                onChange={(e) => { setEmployeeNumber(e.target.value); setErrorMsg(""); setSavedUserId(null); }}
                placeholder="e.g. 6987"
                className="w-full bg-transparent outline-none text-gray-800 placeholder-gray-400 text-sm"
              />
            </TableRow>

            {/* Rights */}
            <TableRow label="Rights">
              <div className="flex flex-col gap-1.5">
                {RIGHTS_OPTIONS.map((opt) => (
                  <label key={opt.value} className="flex items-center gap-2 cursor-pointer text-sm text-gray-700">
                    <input
                      type="radio"
                      name="rights"
                      value={opt.value}
                      checked={rights === opt.value}
                      onChange={() => setRights(opt.value)}
                      className="accent-blue-700"
                    />
                    {opt.label}
                  </label>
                ))}
              </div>
            </TableRow>

            {/* Store Branch Code */}
            <TableRow label="Store Branch Code" alt>
              <div className="flex flex-col gap-1.5">
                {BRANCH_OPTIONS.map((code) => (
                  <label key={code} className="flex items-center gap-2 cursor-pointer text-sm text-gray-700">
                    <input
                      type="radio"
                      name="branchCode"
                      value={code}
                      checked={branchCode === code}
                      onChange={() => setBranchCode(code)}
                      className="accent-blue-700"
                    />
                    {code}
                  </label>
                ))}
              </div>
            </TableRow>

            {/* Empty bottom row */}
            <div className="grid grid-cols-2 h-8" style={{ backgroundColor: "#e8eaed" }}>
              <div className="border-r border-white/30" />
              <div />
            </div>
          </div>

          {/* Action buttons */}
          <div className="flex gap-6 mt-6">
            <button
              onClick={handleActivate}
              disabled={isPending}
              className="flex-1 rounded-xl py-3.5 font-semibold text-gray-700 text-base transition hover:brightness-95 active:scale-[0.98] disabled:opacity-60"
              style={{ backgroundColor: "#f0f1f3" }}
            >
              {isPending && isActive ? "Saving…" : "Active"}
            </button>
            <button
              onClick={handleDeactivate}
              disabled={isPending}
              className="flex-1 rounded-xl py-3.5 font-semibold text-gray-500 text-base transition hover:brightness-95 active:scale-[0.98] disabled:opacity-60"
              style={{ backgroundColor: "#b0b5be" }}
            >
              {isPending && !isActive ? "Saving…" : "Deactivate"}
            </button>
          </div>
        </div>
      </main>
    </div>
  );
}

/* ── Shared table row ── */
function TableRow({ label, children, alt }: { label: string; children: React.ReactNode; alt?: boolean }) {
  return (
    <div
      className="grid grid-cols-2 border-t border-white/10"
      style={{ backgroundColor: alt ? "#dde0e6" : "#e8eaed" }}
    >
      <div className="px-5 py-3 text-sm text-gray-700 font-medium border-r border-white/30 flex items-start pt-3.5">
        {label}
      </div>
      <div className="px-5 py-3">
        {children}
      </div>
    </div>
  );
}
