import { useEffect, useState } from "react";
import { useLocation } from "wouter";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";
import PageHeader from "@/components/PageHeader";
import { useToast } from "@/hooks/use-toast";

const API_BASE = import.meta.env.BASE_URL.replace(/\/$/, "").replace(/\/[^/]*$/, "") + "/api";

interface AdminUser { username: string; }

interface ReportOption {
  key:   string;
  label: string;
}

interface ReportType {
  name:    string;
  options: ReportOption[];
}

const REPORT_TYPES: ReportType[] = [
  {
    name: "Fitting Room Stats",
    options: [
      { key: "productCodes",      label: "Product Codes"      },
      { key: "fittingRoomAlerts", label: "Fitting Room Alerts" },
      { key: "alertsAttendants",  label: "Alerts Attendants"  },
    ],
  },
  {
    name: "Branch Stats",
    options: [
      { key: "mainEntranceAlerts", label: "Main Fitting Room Entrance Alerts" },
      { key: "alertsAttendants",   label: "Alerts Attendants"                 },
    ],
  },
  {
    name: "Verbal",
    options: [
      { key: "alertResponse", label: "Fitting Room alert response" },
    ],
  },
];

type SelectionMap = Record<string, Record<string, boolean>>;

function authHeaders() {
  const token = localStorage.getItem("sfr_admin_token");
  return { "Content-Type": "application/json", Authorization: `Bearer ${token}` };
}

export default function Reports() {
  const [, setLocation]         = useLocation();
  const [admin, setAdmin]       = useState<AdminUser | null>(null);
  const [branches, setBranches] = useState<string[]>([]);
  const [branch, setBranch]     = useState("");
  const [isGenerating, setIsGenerating] = useState(false);
  const { toast } = useToast();

  // selection[reportName][optionKey] = boolean
  const [selection, setSelection] = useState<SelectionMap>(() => {
    const init: SelectionMap = {};
    for (const rt of REPORT_TYPES) {
      init[rt.name] = {};
      for (const opt of rt.options) init[rt.name][opt.key] = false;
    }
    return init;
  });

  useEffect(() => {
    const token   = localStorage.getItem("sfr_admin_token");
    const userStr = localStorage.getItem("sfr_admin_user");
    if (!token || !userStr) { setLocation("/login"); return; }
    try { setAdmin(JSON.parse(userStr)); } catch { setLocation("/login"); }
  }, [setLocation]);

  useEffect(() => {
    if (!admin) return;
    fetch(`${API_BASE}/fitting-rooms/branches`, { headers: authHeaders() })
      .then(r => r.json()).then(setBranches).catch(() => {});
  }, [admin]);

  const toggle = (reportName: string, key: string) => {
    setSelection(prev => ({
      ...prev,
      [reportName]: { ...prev[reportName], [key]: !prev[reportName][key] },
    }));
  };

  const hasAnySelection = Object.values(selection).some(opts =>
    Object.values(opts).some(Boolean)
  );

  const generatePDF = async () => {
    if (!hasAnySelection) {
      toast({ title: "Nothing selected", description: "Please tick at least one column option.", variant: "destructive" });
      return;
    }

    setIsGenerating(true);

    try {
      // Fetch fitting rooms data if a branch is selected
      let rooms: { name: string; roomId: string; status: string; location: string }[] = [];
      if (branch) {
        const res = await fetch(`${API_BASE}/fitting-rooms?branchCode=${encodeURIComponent(branch)}`, { headers: authHeaders() });
        if (res.ok) rooms = await res.json();
      }

      const doc  = new jsPDF({ orientation: "landscape", unit: "mm", format: "a4" });
      const now  = new Date();
      const dateStr = `${String(now.getDate()).padStart(2,"0")}-${["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"][now.getMonth()]}-${now.getFullYear()}`;
      const timeStr = `${String(now.getHours()).padStart(2,"0")}:${String(now.getMinutes()).padStart(2,"0")}`;

      let yPos = 15;
      const pageW = doc.internal.pageSize.getWidth();

      // Header
      doc.setFontSize(16);
      doc.setFont("helvetica", "bold");
      doc.setTextColor(30, 63, 122);
      doc.text("Smart Fitting Room — Report", 14, yPos);
      yPos += 7;

      doc.setFontSize(9);
      doc.setFont("helvetica", "normal");
      doc.setTextColor(80, 80, 80);
      doc.text(`Generated: ${dateStr} ${timeStr}  |  Branch: ${branch || "All branches"}  |  Generated by: ${admin?.username ?? ""}`, 14, yPos);
      yPos += 8;

      // Iterate selected report types
      for (const rt of REPORT_TYPES) {
        const selectedOpts = rt.options.filter(o => selection[rt.name][o.key]);
        if (selectedOpts.length === 0) continue;

        // Section title
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(30, 63, 122);
        doc.text(rt.name, 14, yPos);
        yPos += 4;

        // Build table columns & rows based on report type
        let head: string[][] = [];
        let body: string[][] = [];

        if (rt.name === "Fitting Room Stats") {
          const cols = ["Fitting Room", "Room ID", "Status", "Location"];
          const optCols: string[] = [];
          if (selection[rt.name].productCodes)      { cols.push("Product Codes");      optCols.push("productCodes"); }
          if (selection[rt.name].fittingRoomAlerts)  { cols.push("Fitting Room Alerts"); optCols.push("fittingRoomAlerts"); }
          if (selection[rt.name].alertsAttendants)   { cols.push("Alerts Attendants");   optCols.push("alertsAttendants"); }
          head = [cols];
          body = rooms.length > 0
            ? rooms.map(r => {
                const row = [r.name, r.roomId, r.status.charAt(0).toUpperCase() + r.status.slice(1), r.location || "—"];
                if (optCols.includes("productCodes"))     row.push("—");
                if (optCols.includes("fittingRoomAlerts")) row.push("0");
                if (optCols.includes("alertsAttendants"))  row.push("—");
                return row;
              })
            : [["No fitting rooms found for this branch", "", "", "", ...optCols.map(() => "")]];
        } else if (rt.name === "Branch Stats") {
          const cols = ["Branch Code", "Total Rooms", "Available", "Occupied", "Alert"];
          if (selection[rt.name].mainEntranceAlerts) cols.push("Main Entrance Alerts");
          if (selection[rt.name].alertsAttendants)   cols.push("Alerts Attendants");
          head = [cols];
          const available  = rooms.filter(r => r.status === "available").length;
          const occupied   = rooms.filter(r => r.status === "occupied").length;
          const alertCount = rooms.filter(r => r.status === "alert").length;
          const row = [branch || "—", String(rooms.length), String(available), String(occupied), String(alertCount)];
          if (selection[rt.name].mainEntranceAlerts) row.push("0");
          if (selection[rt.name].alertsAttendants)   row.push("—");
          body = [row];
        } else if (rt.name === "Verbal") {
          head = [["Fitting Room", "Room ID", "Status", "Location", "Alert Response"]];
          body = rooms.length > 0
            ? rooms.map(r => [
                r.name, r.roomId,
                r.status.charAt(0).toUpperCase() + r.status.slice(1),
                r.location || "—",
                r.status === "alert" ? "Alert raised — attendant required" : r.status === "occupied" ? "Room occupied" : "Room available",
              ])
            : [["No fitting rooms found", "", "", "", ""]];
        }

        autoTable(doc, {
          startY: yPos,
          head,
          body,
          theme: "grid",
          headStyles: { fillColor: [30, 63, 122], textColor: 255, fontStyle: "bold", fontSize: 9 },
          bodyStyles: { fontSize: 8.5, textColor: [40, 40, 40] },
          alternateRowStyles: { fillColor: [240, 244, 250] },
          margin: { left: 14, right: 14 },
          tableWidth: pageW - 28,
        });

        yPos = (doc as any).lastAutoTable.finalY + 10;
      }

      // Footer on each page
      const totalPages = (doc as any).internal.getNumberOfPages();
      for (let i = 1; i <= totalPages; i++) {
        doc.setPage(i);
        doc.setFontSize(8);
        doc.setTextColor(150);
        doc.text(`Page ${i} of ${totalPages}  —  Smart Fitting Room Management System`, 14, doc.internal.pageSize.getHeight() - 6);
      }

      doc.save(`SFR_Report_${branch || "All"}_${dateStr}.pdf`);
      toast({ title: "Downloaded", description: "Your report PDF has been saved." });
    } catch (err) {
      toast({ title: "Error", description: "Failed to generate report.", variant: "destructive" });
    } finally {
      setIsGenerating(false);
    }
  };

  if (!admin) return null;

  return (
    <div className="min-h-screen w-full flex flex-col" style={{ backgroundColor: "#1e3f7a" }}>
      <PageHeader title={`Account: (${admin.username})`} breadcrumb="Home/Reports" />

      <main className="flex-1 flex flex-col px-8 pt-2 pb-8">

        {/* Branch selector */}
        <div className="flex items-stretch mb-6 rounded-lg overflow-hidden w-full max-w-xl" style={{ border: "2px solid #fff" }}>
          <div className="flex items-center px-5 font-bold text-white text-sm" style={{ backgroundColor: "#111827", minWidth: "130px" }}>
            Branch Code
          </div>
          <div className="relative flex-1">
            <select
              value={branch}
              onChange={e => setBranch(e.target.value)}
              className="w-full h-full appearance-none px-4 py-3 text-gray-500 text-sm font-medium focus:outline-none"
              style={{ backgroundColor: "#e0e0e0" }}
            >
              <option value="">Select branch code</option>
              {branches.map(b => <option key={b} value={b}>{b}</option>)}
            </select>
            <div className="pointer-events-none absolute right-3 top-1/2 -translate-y-1/2">
              <svg viewBox="0 0 16 10" fill="none" className="w-4 h-3">
                <path d="M1 1l7 8 7-8" stroke="#555" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
              </svg>
            </div>
          </div>
        </div>

        {/* Report table */}
        <div className="w-full rounded-xl overflow-hidden border border-white/10 mb-8">
          {/* Header */}
          <div className="grid text-white font-bold text-sm" style={{ backgroundColor: "#111827", gridTemplateColumns: "1fr 1.6fr" }}>
            <div className="flex items-center px-5 py-3 border-r border-white/10">Report Type</div>
            <div className="flex items-center px-5 py-3">Column Options</div>
          </div>

          {/* Rows */}
          {REPORT_TYPES.map((rt, idx) => (
            <div
              key={rt.name}
              className="grid border-t border-white/10"
              style={{
                gridTemplateColumns: "1fr 1.6fr",
                backgroundColor: idx % 2 === 0 ? "#e8eaed" : "#d8dbe2",
              }}
            >
              {/* Report name */}
              <div className="flex items-center px-5 py-4 border-r border-white/20 text-sm font-medium text-gray-800">
                {rt.name}
              </div>

              {/* Checkboxes */}
              <div className="flex flex-col gap-2 px-5 py-4">
                {rt.options.map(opt => {
                  const checked = selection[rt.name][opt.key];
                  return (
                    <label key={opt.key} className="flex items-center gap-3 cursor-pointer group">
                      <button
                        onClick={() => toggle(rt.name, opt.key)}
                        role="checkbox"
                        aria-checked={checked}
                        className="w-5 h-5 shrink-0 border-2 rounded flex items-center justify-center transition"
                        style={{
                          backgroundColor: checked ? "#1e3f7a" : "#fff",
                          borderColor:     checked ? "#1e3f7a" : "#888",
                        }}
                      >
                        {checked && (
                          <svg viewBox="0 0 12 10" fill="none" className="w-3 h-3">
                            <path d="M1 5l3.5 3.5L11 1" stroke="white" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round" />
                          </svg>
                        )}
                      </button>
                      <span
                        className="text-sm text-gray-800 group-hover:text-gray-900 transition select-none"
                        onClick={() => toggle(rt.name, opt.key)}
                      >
                        {opt.label}
                      </span>
                    </label>
                  );
                })}
              </div>
            </div>
          ))}
        </div>

        {/* Download button */}
        <div className="flex justify-center">
          <button
            onClick={generatePDF}
            disabled={isGenerating}
            className="rounded-xl px-20 py-3.5 font-semibold text-gray-700 text-base transition hover:brightness-95 active:scale-[0.98]"
            style={{ backgroundColor: "#ffffff", minWidth: "220px", opacity: isGenerating ? 0.7 : 1 }}
          >
            {isGenerating ? "Generating…" : "Download"}
          </button>
        </div>
      </main>
    </div>
  );
}
